version: "3.1"

services:
  postgres-dev:
    image: postgres
    container_name: postgres-demo-db
    # volumes:
    #   - "./postgres-db/data/:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: postgres-db
