#This workflow will build a Java project with Maven
name: A workflow for my Hello World spring project
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn -B deploy --file pom.xml