
name: A workflow for my Hello World spring project
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    services:
      docker-dind-container:
        image: docker:dind
        env:
          DOCKER_HOST: tcp://docker:2376
          DOCKER_TLS_CERTDIR: /certs
          DOCKER_CERT_PATH: /certs/client
          DOCKER_TLS_VERIFY: 1
          DOCKER_DRIVER: overlay2
          MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Publish package
        run: mvn $MAVEN_CLI_OPTS clean deploy -Dit.postgresql.host=docker-dind-container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copying target jar
        run: |
          mkdir myTarget
          cp target/*.jar myTarget
      - name: Uploading jar
        uses: actions/upload-artifact@v2
        with:
          name: myPackage
          path: myTarget


